/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/content-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content types and the field schema forms are generated from. */
        get: operations["listContentTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content. */
        get: operations["listContents"];
        put?: never;
        /** Write a new item. */
        post: operations["createContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one item, including its source body. */
        get: operations["getContent"];
        /** Replace an item, refusing an edit made against a replaced version. */
        put: operations["updateContent"];
        post?: never;
        /** Remove an item and everything its bundle owns. */
        delete: operations["deleteContent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a file beside a page and report the link that reaches it. */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{id}/media/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a file from a page's bundle. */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render a draft through the real theme, without storing it. */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the open project. */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List taxonomies and how many terms each holds. */
        get: operations["listTaxonomies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/{taxonomy}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count one taxonomy's terms over a filtered set. */
        get: operations["listTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Conflict: {
            actual_revision: string;
            expected_revision: string;
            theirs?: components["schemas"]["Item"];
        };
        ConflictBody: {
            conflict: components["schemas"]["Conflict"];
            error: components["schemas"]["ErrorDetail"];
        };
        ContentType: {
            dir: string;
            fields?: components["schemas"]["Field"][];
            kind: string;
            label: string;
            layout: string;
            route: string;
            sortable?: string[];
            taxonomies?: string[];
        };
        ContentTypeList: {
            has_more: boolean;
            items: components["schemas"]["ContentType"][];
            next_cursor?: string;
            total?: number;
        };
        Draft: {
            aliases?: string[];
            body: string;
            kind: string;
            locale?: string;
            meta?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            published_at?: string;
            slug?: string;
            status: string;
            taxonomies?: {
                [key: string]: string[];
            };
            title: string;
        };
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            code: string;
            field?: string;
            message: string;
        };
        Field: {
            default?: unknown;
            fields?: components["schemas"]["Field"][];
            help?: string;
            key: string;
            label?: string;
            language?: string;
            max?: number;
            min?: number;
            options?: components["schemas"]["Option"][];
            placeholder?: string;
            required?: boolean;
            showIf?: {
                [key: string]: unknown;
            };
            type: string;
        };
        Item: {
            aliases?: string[];
            body: string;
            body_format: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string;
            excerpt?: string;
            id: string;
            kind: string;
            locale?: string;
            locator?: string;
            meta?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            published_at?: string;
            revision: string;
            slug: string;
            status: string;
            taxonomies?: {
                [key: string]: string[];
            };
            title: string;
            /** Format: date-time */
            updated_at: string;
            url: string;
        };
        Media: {
            link: string;
            name: string;
            path: string;
            size: number;
            type?: string;
            url: string;
        };
        Option: {
            label: string;
            value: string;
        };
        SiteInfo: {
            base_url: string;
            counts?: {
                [key: string]: number;
            };
            description?: string;
            language?: string;
            problems?: string[];
            runtime: string;
            store: string;
            theme?: string;
            title: string;
            version?: string;
        };
        Summary: {
            /** Format: date-time */
            created_at: string;
            excerpt?: string;
            id: string;
            kind: string;
            locale?: string;
            locator?: string;
            /** Format: date-time */
            published_at?: string;
            revision: string;
            slug: string;
            status: string;
            taxonomies?: {
                [key: string]: string[];
            };
            title: string;
            /** Format: date-time */
            updated_at: string;
            url: string;
        };
        SummaryList: {
            has_more: boolean;
            items: components["schemas"]["Summary"][];
            next_cursor?: string;
            total?: number;
        };
        Taxonomy: {
            name: string;
            terms: number;
            url: string;
        };
        TaxonomyList: {
            has_more: boolean;
            items: components["schemas"]["Taxonomy"][];
            next_cursor?: string;
            total?: number;
        };
        TermCount: {
            count: number;
            term: string;
            url: string;
        };
        TermCountList: {
            has_more: boolean;
            items: components["schemas"]["TermCount"][];
            next_cursor?: string;
            total?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listContentTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The registry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTypeList"];
                };
            };
        };
    };
    listContents: {
        parameters: {
            query?: {
                /** @description Content kind, repeatable. */
                kind?: string[];
                /** @description draft, scheduled, published or archived, repeatable. */
                status?: string[];
                /** @description Locale, repeatable. */
                locale?: string[];
                /** @description Restrict to these ids, repeatable. */
                id?: string[];
                /** @description taxonomy:term the item must carry at least one of, repeatable. */
                term?: string[];
                /** @description taxonomy:term the item must carry all of, repeatable. */
                term_all?: string[];
                /** @description Earliest publication time, RFC 3339. */
                published_from?: string;
                /** @description Latest publication time, RFC 3339. */
                published_to?: string;
                /** @description Earliest update time, RFC 3339. */
                updated_from?: string;
                /** @description Latest update time, RFC 3339. */
                updated_to?: string;
                /** @description Free text over title, excerpt and body. */
                q?: string;
                /** @description Include soft deleted items. */
                include_deleted?: boolean;
                /** @description Comma separated keys, '-' for descending, e.g. -published_at,title. */
                sort?: string;
                /** @description Opaque position from a previous response. There is no offset. */
                cursor?: string;
                /** @description Items per page, capped by the server. */
                limit?: number;
                /** @description Also report the size of the whole filtered set. */
                count?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryList"];
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Draft"];
            };
        };
        responses: {
            /** @description The item as stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item. ETag carries its revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    updateContent: {
        parameters: {
            query?: never;
            header: {
                /** @description The revision this edit was made against, as returned in ETag. Required: without it a save would overwrite whatever is there. */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Draft"];
            };
        };
        responses: {
            /** @description The item as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The item changed since it was loaded. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictBody"];
                };
            };
            /** @description Failed. */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    deleteContent: {
        parameters: {
            query?: never;
            header: {
                /** @description The revision this edit was made against, as returned in ETag. Required: without it a save would overwrite whatever is there. */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The item changed since it was loaded. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictBody"];
                };
            };
            /** @description Failed. */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The stored file. The name may differ from the one sent, since an upload never replaces a file of the same name. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: {
                /** @description The item being edited, so its own images resolve. */
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Draft"];
            };
        };
        responses: {
            /** @description The rendered page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteInfo"];
                };
            };
        };
    };
    listTaxonomies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The taxonomies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyList"];
                };
            };
        };
    };
    listTerms: {
        parameters: {
            query?: {
                /** @description Content kind, repeatable. */
                kind?: string[];
                /** @description draft, scheduled, published or archived, repeatable. */
                status?: string[];
                /** @description Locale, repeatable. */
                locale?: string[];
                /** @description Restrict to these ids, repeatable. */
                id?: string[];
                /** @description taxonomy:term the item must carry at least one of, repeatable. */
                term?: string[];
                /** @description taxonomy:term the item must carry all of, repeatable. */
                term_all?: string[];
                /** @description Earliest publication time, RFC 3339. */
                published_from?: string;
                /** @description Latest publication time, RFC 3339. */
                published_to?: string;
                /** @description Earliest update time, RFC 3339. */
                updated_from?: string;
                /** @description Latest update time, RFC 3339. */
                updated_to?: string;
                /** @description Free text over title, excerpt and body. */
                q?: string;
                /** @description Include soft deleted items. */
                include_deleted?: boolean;
                /** @description Comma separated keys, '-' for descending, e.g. -published_at,title. */
                sort?: string;
                /** @description Opaque position from a previous response. There is no offset. */
                cursor?: string;
                /** @description Items per page, capped by the server. */
                limit?: number;
                /** @description Also report the size of the whole filtered set. */
                count?: boolean;
            };
            header?: never;
            path: {
                taxonomy: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Term counts, most used first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermCountList"];
                };
            };
            /** @description Failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Failed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
