package storage

import (
	"context"
	"fmt"
	"io"
	"time"
)

// StorageDriver is the interface every storage backend must implement.
// Local disks and S3-compatible object stores are both abstracted through this interface
// so upstream code is agnostic to the underlying storage.
type StorageDriver interface {
	// Put writes the file contents to the backend.
	// key is the object path generated by upstream code (e.g. "2024/01/abc12345/uuid.jpg"),
	// size is the byte count, and mimeType is the content type.
	Put(ctx context.Context, key string, reader io.Reader, size int64, mimeType string) error

	// Get reads the file contents from the backend.
	// The caller must close the returned ReadCloser. The second return value is the byte size.
	Get(ctx context.Context, key string) (io.ReadCloser, int64, error)

	// Delete removes the file from the backend.
	// Missing files must return nil so the operation is idempotent.
	Delete(ctx context.Context, key string) error

	// Exists reports whether the given key is present in the backend.
	Exists(ctx context.Context, key string) (bool, error)

	// URL returns the public access URL for the given key.
	// Backends configured with a CDN domain return the CDN URL.
	URL(key string) string

	// SignedURL returns a time-limited pre-signed access URL.
	// Used primarily for temporary access to private buckets.
	SignedURL(ctx context.Context, key string, expires time.Duration) (string, error)
}

// Driver-type constants. S3-compatible drivers (oss/cos/obs/bos) keep distinct values in the
// database so the frontend can render distinct branding, while all sharing the S3 wire protocol.
const (
	DriverLocal = "local"
	DriverS3    = "s3"
	DriverOSS   = "oss" // Alibaba Cloud OSS
	DriverCOS   = "cos" // Tencent Cloud COS
	DriverOBS   = "obs" // Huawei Cloud OBS
	DriverBOS   = "bos" // Baidu Cloud BOS
	DriverFTP   = "ftp"
)

// IsS3Compatible reports whether the driver speaks the S3-compatible protocol.
func IsS3Compatible(driver string) bool {
	switch driver {
	case DriverS3, DriverOSS, DriverCOS, DriverOBS, DriverBOS:
		return true
	}
	return false
}

// StorageConfig is the runtime storage configuration, deserialised from the config column
// of the storage_configs table.
type StorageConfig struct {
	Driver string       `json:"driver"`          // driver type: local / s3 / oss / cos / obs / bos / ftp
	Local  *LocalConfig `json:"local,omitempty"` // required when driver is local
	S3     *S3Config    `json:"s3,omitempty"`    // required when driver is s3/oss/cos/obs/bos
	FTP    *FTPConfig   `json:"ftp,omitempty"`   // required when driver is ftp
}

// LocalConfig is the configuration for the local filesystem driver.
type LocalConfig struct {
	BasePath string `json:"base_path"` // absolute root directory for file storage
	BaseURL  string `json:"base_url"`  // access URL prefix (e.g. "https://kite.plus/files")
}

// S3Config is the configuration for any S3-compatible driver.
// The Endpoint and flags make it cover Aliyun OSS, Tencent COS, Cloudflare R2, MinIO, etc.
type S3Config struct {
	Endpoint        string `json:"endpoint"`          // service endpoint (e.g. "oss-cn-hangzhou.aliyuncs.com")
	Region          string `json:"region"`            // region (e.g. "cn-hangzhou", "auto")
	Bucket          string `json:"bucket"`            // bucket name
	AccessKeyID     string `json:"access_key_id"`     // access key ID
	SecretAccessKey string `json:"secret_access_key"` // access key secret
	BaseURL         string `json:"base_url"`          // optional CDN domain (e.g. "https://cdn.example.com")
	ForcePathStyle  bool   `json:"force_path_style"`  // use path-style access; required by MinIO
}

// FTPConfig is the configuration for the FTP driver.
type FTPConfig struct {
	Host     string `json:"host"`      // FTP host (no port)
	Port     int    `json:"port"`      // FTP port, defaults to 21
	Username string `json:"username"`  // login username
	Password string `json:"password"`  // login password
	BasePath string `json:"base_path"` // remote root directory
	BaseURL  string `json:"base_url"`  // public access prefix (FTP has no native URL; pair with an HTTP reverse proxy)
}

// NewDriver builds the matching driver instance for the given configuration.
func NewDriver(cfg StorageConfig) (StorageDriver, error) {
	switch cfg.Driver {
	case DriverS3, DriverOSS, DriverCOS, DriverOBS, DriverBOS:
		if cfg.S3 == nil {
			return nil, fmt.Errorf("storage config: driver is %s but s3 config is nil", cfg.Driver)
		}
		return NewS3Driver(*cfg.S3)
	case DriverLocal:
		if cfg.Local == nil {
			return nil, fmt.Errorf("storage config: driver is local but local config is nil")
		}
		return NewLocalDriver(*cfg.Local)
	case DriverFTP:
		if cfg.FTP == nil {
			return nil, fmt.Errorf("storage config: driver is ftp but ftp config is nil")
		}
		return NewFTPDriver(*cfg.FTP)
	default:
		return nil, fmt.Errorf("storage config: unknown driver %q", cfg.Driver)
	}
}
