/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDeployRouteImport } from './routes/_authenticated/deploy'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedThemeRouteImport } from './routes/_authenticated/theme'
import { Route as AuthenticatedContentKindRouteRouteImport } from './routes/_authenticated/content/$kind/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsThemeRouteImport } from './routes/_authenticated/settings/theme'
import { Route as AuthenticatedTaxonomiesIndexRouteImport } from './routes/_authenticated/taxonomies/index'
import { Route as AuthenticatedTaxonomiesTaxonomyRouteImport } from './routes/_authenticated/taxonomies/$taxonomy'
import { Route as AuthenticatedContentKindIndexRouteImport } from './routes/_authenticated/content/$kind/index'
import { Route as AuthenticatedContentKindIdRouteImport } from './routes/_authenticated/content/$kind/$id'
import { Route as AuthenticatedSettingsThemeNameRouteImport } from './routes/_authenticated/settings_/theme/$name'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeployRoute = AuthenticatedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThemeRoute = AuthenticatedThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentKindRouteRoute =
  AuthenticatedContentKindRouteRouteImport.update({
    id: '/content/$kind',
    path: '/content/$kind',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsThemeRoute =
  AuthenticatedSettingsThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTaxonomiesIndexRoute =
  AuthenticatedTaxonomiesIndexRouteImport.update({
    id: '/taxonomies/',
    path: '/taxonomies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaxonomiesTaxonomyRoute =
  AuthenticatedTaxonomiesTaxonomyRouteImport.update({
    id: '/taxonomies/$taxonomy',
    path: '/taxonomies/$taxonomy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentKindIndexRoute =
  AuthenticatedContentKindIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContentKindRouteRoute,
  } as any)
const AuthenticatedContentKindIdRoute =
  AuthenticatedContentKindIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContentKindRouteRoute,
  } as any)
const AuthenticatedSettingsThemeNameRoute =
  AuthenticatedSettingsThemeNameRouteImport.update({
    id: '/settings_/theme/$name',
    path: '/settings/theme/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/theme': typeof AuthenticatedThemeRoute
  '/content/$kind': typeof AuthenticatedContentKindRouteRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/taxonomies/$taxonomy': typeof AuthenticatedTaxonomiesTaxonomyRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/taxonomies/': typeof AuthenticatedTaxonomiesIndexRoute
  '/content/$kind/$id': typeof AuthenticatedContentKindIdRoute
  '/settings/theme/$name': typeof AuthenticatedSettingsThemeNameRoute
  '/content/$kind/': typeof AuthenticatedContentKindIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/theme': typeof AuthenticatedThemeRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/taxonomies/$taxonomy': typeof AuthenticatedTaxonomiesTaxonomyRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/taxonomies': typeof AuthenticatedTaxonomiesIndexRoute
  '/content/$kind/$id': typeof AuthenticatedContentKindIdRoute
  '/settings/theme/$name': typeof AuthenticatedSettingsThemeNameRoute
  '/content/$kind': typeof AuthenticatedContentKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/deploy': typeof AuthenticatedDeployRoute
  '/_authenticated/theme': typeof AuthenticatedThemeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/content/$kind': typeof AuthenticatedContentKindRouteRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/_authenticated/taxonomies/$taxonomy': typeof AuthenticatedTaxonomiesTaxonomyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/taxonomies/': typeof AuthenticatedTaxonomiesIndexRoute
  '/_authenticated/content/$kind/$id': typeof AuthenticatedContentKindIdRoute
  '/_authenticated/settings_/theme/$name': typeof AuthenticatedSettingsThemeNameRoute
  '/_authenticated/content/$kind/': typeof AuthenticatedContentKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/setup'
    | '/sign-in'
    | '/deploy'
    | '/theme'
    | '/content/$kind'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/theme'
    | '/taxonomies/$taxonomy'
    | '/settings/'
    | '/taxonomies/'
    | '/content/$kind/$id'
    | '/settings/theme/$name'
    | '/content/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/sign-in'
    | '/deploy'
    | '/theme'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/theme'
    | '/taxonomies/$taxonomy'
    | '/settings'
    | '/taxonomies'
    | '/content/$kind/$id'
    | '/settings/theme/$name'
    | '/content/$kind'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/_authenticated/deploy'
    | '/_authenticated/theme'
    | '/_authenticated/'
    | '/_authenticated/content/$kind'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/theme'
    | '/_authenticated/taxonomies/$taxonomy'
    | '/_authenticated/settings/'
    | '/_authenticated/taxonomies/'
    | '/_authenticated/content/$kind/$id'
    | '/_authenticated/settings_/theme/$name'
    | '/_authenticated/content/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deploy': {
      id: '/_authenticated/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthenticatedDeployRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theme': {
      id: '/_authenticated/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof AuthenticatedThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/$kind': {
      id: '/_authenticated/content/$kind'
      path: '/content/$kind'
      fullPath: '/content/$kind'
      preLoaderRoute: typeof AuthenticatedContentKindRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/theme': {
      id: '/_authenticated/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof AuthenticatedSettingsThemeRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/taxonomies/': {
      id: '/_authenticated/taxonomies/'
      path: '/taxonomies'
      fullPath: '/taxonomies/'
      preLoaderRoute: typeof AuthenticatedTaxonomiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taxonomies/$taxonomy': {
      id: '/_authenticated/taxonomies/$taxonomy'
      path: '/taxonomies/$taxonomy'
      fullPath: '/taxonomies/$taxonomy'
      preLoaderRoute: typeof AuthenticatedTaxonomiesTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/$kind/': {
      id: '/_authenticated/content/$kind/'
      path: '/'
      fullPath: '/content/$kind/'
      preLoaderRoute: typeof AuthenticatedContentKindIndexRouteImport
      parentRoute: typeof AuthenticatedContentKindRouteRoute
    }
    '/_authenticated/content/$kind/$id': {
      id: '/_authenticated/content/$kind/$id'
      path: '/$id'
      fullPath: '/content/$kind/$id'
      preLoaderRoute: typeof AuthenticatedContentKindIdRouteImport
      parentRoute: typeof AuthenticatedContentKindRouteRoute
    }
    '/_authenticated/settings_/theme/$name': {
      id: '/_authenticated/settings_/theme/$name'
      path: '/settings/theme/$name'
      fullPath: '/settings/theme/$name'
      preLoaderRoute: typeof AuthenticatedSettingsThemeNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsThemeRoute: typeof AuthenticatedSettingsThemeRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsThemeRoute: AuthenticatedSettingsThemeRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedContentKindRouteRouteChildren {
  AuthenticatedContentKindIdRoute: typeof AuthenticatedContentKindIdRoute
  AuthenticatedContentKindIndexRoute: typeof AuthenticatedContentKindIndexRoute
}

const AuthenticatedContentKindRouteRouteChildren: AuthenticatedContentKindRouteRouteChildren =
  {
    AuthenticatedContentKindIdRoute: AuthenticatedContentKindIdRoute,
    AuthenticatedContentKindIndexRoute: AuthenticatedContentKindIndexRoute,
  }

const AuthenticatedContentKindRouteRouteWithChildren =
  AuthenticatedContentKindRouteRoute._addFileChildren(
    AuthenticatedContentKindRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDeployRoute: typeof AuthenticatedDeployRoute
  AuthenticatedThemeRoute: typeof AuthenticatedThemeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContentKindRouteRoute: typeof AuthenticatedContentKindRouteRouteWithChildren
  AuthenticatedTaxonomiesTaxonomyRoute: typeof AuthenticatedTaxonomiesTaxonomyRoute
  AuthenticatedTaxonomiesIndexRoute: typeof AuthenticatedTaxonomiesIndexRoute
  AuthenticatedSettingsThemeNameRoute: typeof AuthenticatedSettingsThemeNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDeployRoute: AuthenticatedDeployRoute,
  AuthenticatedThemeRoute: AuthenticatedThemeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContentKindRouteRoute:
    AuthenticatedContentKindRouteRouteWithChildren,
  AuthenticatedTaxonomiesTaxonomyRoute: AuthenticatedTaxonomiesTaxonomyRoute,
  AuthenticatedTaxonomiesIndexRoute: AuthenticatedTaxonomiesIndexRoute,
  AuthenticatedSettingsThemeNameRoute: AuthenticatedSettingsThemeNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
